#ifndef SURFACE_LIST_H
#define SURFACE_LIST_H
#include <QList>
#include <QString>
#include <QPair>

class SurfaceList : public QList<QPair<QString, int> > //string first for sorting
{
public:
   SurfaceList();
   void moveLast();
   void moveFirst();
   void displayList();
   void saveList() {}
   bool openList() {return false;} //return false on failure
   void setName(QString newName);
private:
   int index;
   QString listName; //gets generated by constructor but can be edited
   bool dirty; //set to false on save, set to true on append or delete
   static int count; //number of lists, default static initialization to zero
};

#endif // SURFACE_LIST_H
